version: '3.4'

services:
   db:
     image: mariadb
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: Pa55Word!4
       MYSQL_DATABASE: urlaubsverwaltung
       MYSQL_USER: urlaubsverwaltung
       MYSQL_PASSWORD: password
     volumes:
      - db-data:/var/lib/mysql
     healthcheck:
       test: "/usr/bin/mysql --user=root --password=Pa55Word!4 --execute \"SHOW DATABASES;\""
       interval: 2s
       timeout: 20s
       retries: 10
   urlaubsverwaltung:
     depends_on:
       - db
     image: fjuette/urlaubsverwaltung:latest
     ports:
       - "8080:8080"
     links:
      - db
     restart: always
     environment: 
       MYSQL_DB_HOST: db
       MYSQL_DB_NAME: urlaubsverwaltung
       MYSQL_DB_USER: urlaubsverwaltung
       MYSQL_DB_PASSWORD: password
       AUTHENTICATION: default
volumes:
  db-data: